---
title: "Shiny Demonstartion"
author: "Brady Johnston"
date: "02/04/2021"
output: 
  html_document:
    code_folding: hide
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


```{r echo = TRUE, attr.source = c('.numberlines', 'startFrom=12')}
library(shiny)
library(stringr)
library(ggplot2)
library(dplyr)
library(plasmapR)
library(shinyWidgets)

`%>%` <- magrittr::`%>%`

plasmid <- readLines("../data/petm20.gb")

sequence <- extract_sequence(plasmid)

sequence <- paste0(sequence, collapse = "")

feat_df <- create_feature_df(get_features(plasmid))
```


```{r inputs, echo=FALSE}
inputPanel(
  knobInput(
    inputId = "rotation", 
    label = "Rotate Map (Degrees)", 
    value = 90, 
    min = 0, 
    max = 360, 
    step = 1
  ),
  # sliderInput(
  #   inputId = "rotation", 
  #   label = "Rotation Angle (Degrees)", 
  #   min = -180, 
  #   max = 180, 
  #   value = 0, 
  #   step = 1
  # ), 
  sliderInput(
    inputId = "repelBox", 
    label = "Label Spacing Size", 
    min = 0, 
    max = 1, 
    value = 0.3
  ), 
  sliderInput(
    inputId = "labelNudge", 
    label = "Nudge Label Distance", 
    min = 0, 
    max = 2, 
    value = 0.8, 
    step = 0.1
  ), 
  sliderInput(
    inputId = "curve", 
    label = "Label Line Curvature", 
    min = 0, 
    max = 30, 
    value = 10, 
    step = 1
  ), 
  colourpicker::colourInput(
    inputId = "labelTextColour", 
    label = "Label Text Colour", 
    value = "black", 
    showColour = "background"
  ), 
  sliderInput(
    inputId = "zoom", 
    label = "Plasmid Zoom", 
    min = 0, 
    max = 5, 
    value = 3
  ), 
  sliderInput(
    inputId = "textSize", 
    label = "Text Size", 
    min = 1, 
    value = 10,
    max = 20, 
    step = 0.2
  ), 
  selectInput(
    inputId = "features", 
    label = "Feature Types Shown", 
    choices = unique(feat_df$type), 
    selected = unique(feat_df$type), 
    multiple = TRUE
  ), 
  textInput(
    inputId = "plasmidName", 
    label = "Plasmid Name", 
    value = "Plasmid Name Here"
  ), 
  sliderInput(
    inputId = "nameSize", 
    label = "Plasmid Name Size", 
    min = 1, 
    max = 10, 
    step = 0.2, 
    value = 3
  )
)
```


```{r plasmap, echo=FALSE}

renderPlot({
  
  feat_df <- feat_df %>% 
    dplyr::filter(type %in% input$features)
  
  arrow_df <- create_arrow_plotting_df(
  df = feat_df,
  middle = 2,
  width = 0.1,
  arrowhead_size = 4,
  # arrow_cutoff = 0.,
  plasmid_length = nchar(sequence)
)

angle_adjustment <- ifelse(input$rotation < 180, input$rotation, -(360 - input$rotation))

labels <- create_labels(feat_df,
              plasmid_length = nchar(sequence),
              spacing_scale = 0.006,
              label_hjust = 0.4,
              rotation = angle_adjustment,
              label_length_cutoff = 0.85)
labels
# split_text_df(100, 50, "testing", 2)

curve <- input$curve


ggplot() +
  geom_hline(yintercept = 2) +
  coord_polar(start = angle_adjustment / 360 * 2 * pi) +
  xlim(c(0, nchar(sequence))) +
  ylim(c(0, input$zoom)) +
  geom_polygon(data = arrow_df,
               aes(
                 x = x,
                 y = y,
                 fill = type,
                 group = index
               ),
               colour = "black") +
  theme_void() +
  theme(legend.position = "") +
  annotate(geom = "text",
           x = 0,
           y = 0,
           label = input$plasmidName,
           size = input$nameSize,
           family = "mono") +
  geom_text(
    data = labels$curved,
    mapping = aes(
      x = pos,
      y = 2,
      angle = angle - angle_adjustment,
      label = char
    ),
    family = "mono"
  ) +
  ggrepel::geom_label_repel(
    data = labels$annotations,
    mapping = aes(
      x = middle,
      y = 2.1,
      label = name, 
      fill = type
    ),
    colour = input$labelTextColour,
    segment.color = "black",
    size = input$textSize/.pt,
    nudge_y = input$labelNudge,
    ylim = c(2.2, 5),
    box.padding = input$repelBox,
    max.overlaps = 20,
    segment.curvature = 1 * 10 ^ (-curve),
    segment.inflect = FALSE,
    segment.square = TRUE,
    # direction = "y",
    hjust = 0.5
    ) +
  geom_polygon(
    data = create_arrow_positions(5209, 7503, 1.6, 0.1, 7800),
     aes(x = x,
         y = y),
    fill = "#b1fc03",
    colour = "black"
  ) +
  # scale_color_discrete(
  #   name = "type", 
  #   aesthetics = c("segment.color")
  # )
  geom_text(
    data = plasmapR::create_labels(
      df = data.frame(
        name = "Expressed Construct",
        start = 5209,
        end = 7503
      ),
      plasmid_length = 7800,
      spacing_scale = 0.007
    )$curved,
    aes(
      x = pos,
      y = 1.6,
      angle = angle - angle_adjustment,
      label = char
    )
  )
}, 
width = 800, 
height = 1000, 
res = 75)
```


